version: "3.8"
name: infinimesh-debug-env

services:
  db:
    image: arangodb/arangodb:latest
    restart: always
    environment:
      ARANGO_ROOT_PASSWORD: openSesame
    ports:
      - 8529:8529
    volumes:
      - data:/var/lib/arangodb3

  redis:
    network_mode: host
    image: redis:latest
    ports:
      - 6379:6379
    labels:
      - traefik.enable=false
    command: [ "redis-server", "--appendonly", "yes" ]

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
     - 5672:5672
     - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"

volumes:
  data: