// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apiserver/apipb/api.proto

package apipb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	nodepb "github.com/infinimesh/infinimesh/pkg/node/nodepb"
	registrypb "github.com/infinimesh/infinimesh/pkg/registry/registrypb"
	shadowpb "github.com/infinimesh/infinimesh/pkg/shadow/shadowpb"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TokenRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a22a27722afd30, []int{0}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type TokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a22a27722afd30, []int{1}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

func (m *TokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ListObjectsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListObjectsRequest) Reset()         { *m = ListObjectsRequest{} }
func (m *ListObjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListObjectsRequest) ProtoMessage()    {}
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a22a27722afd30, []int{2}
}

func (m *ListObjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListObjectsRequest.Unmarshal(m, b)
}
func (m *ListObjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListObjectsRequest.Marshal(b, m, deterministic)
}
func (m *ListObjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListObjectsRequest.Merge(m, src)
}
func (m *ListObjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListObjectsRequest.Size(m)
}
func (m *ListObjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListObjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListObjectsRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TokenRequest)(nil), "infinimesh.api.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "infinimesh.api.TokenResponse")
	proto.RegisterType((*ListObjectsRequest)(nil), "infinimesh.api.ListObjectsRequest")
}

func init() { proto.RegisterFile("pkg/apiserver/apipb/api.proto", fileDescriptor_06a22a27722afd30) }

var fileDescriptor_06a22a27722afd30 = []byte{
	// 745 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x41, 0x4f, 0x1b, 0x47,
	0x14, 0xd6, 0x02, 0x36, 0x74, 0x28, 0x2d, 0x1e, 0xb9, 0x2d, 0x5d, 0xd9, 0xd4, 0x5a, 0x41, 0x4b,
	0x5d, 0xbc, 0x4b, 0xdd, 0x72, 0xf1, 0xa1, 0x2a, 0xc1, 0x0a, 0x42, 0x8a, 0x12, 0x84, 0x89, 0x22,
	0x71, 0x89, 0x66, 0xbd, 0x8f, 0xf5, 0x80, 0xbd, 0x33, 0x99, 0x19, 0x63, 0x25, 0x11, 0x97, 0xfc,
	0x84, 0xe4, 0x96, 0x6b, 0xee, 0x39, 0xe4, 0x96, 0x53, 0x7e, 0x44, 0xfe, 0x42, 0xfe, 0x46, 0xa4,
	0x68, 0x67, 0x67, 0x8d, 0x37, 0x36, 0xd8, 0xb9, 0x78, 0xdf, 0xcc, 0xfb, 0xde, 0xfb, 0xbe, 0x79,
	0xcf, 0xf3, 0x06, 0x95, 0xf9, 0x45, 0xe8, 0x11, 0x4e, 0x25, 0x88, 0x4b, 0x10, 0xb1, 0xc5, 0xfd,
	0xf8, 0xd7, 0xe5, 0x82, 0x29, 0x86, 0x7f, 0xa0, 0xd1, 0x19, 0x8d, 0x68, 0x0f, 0x64, 0xc7, 0x25,
	0x9c, 0xda, 0xb5, 0x18, 0x2e, 0x20, 0xa4, 0x52, 0x89, 0xa7, 0x43, 0x83, 0xfb, 0x5e, 0x00, 0x97,
	0xb4, 0x0d, 0x8f, 0xd3, 0x9d, 0x24, 0xdc, 0xae, 0xc4, 0x70, 0xd9, 0x21, 0x01, 0x1b, 0x98, 0x0f,
	0xf7, 0x8d, 0x61, 0x10, 0x76, 0x8c, 0x88, 0x58, 0x00, 0xfa, 0x87, 0xfb, 0xfa, 0x63, 0x7c, 0xdb,
	0xfa, 0xd3, 0xae, 0x85, 0x10, 0xd5, 0xe4, 0x80, 0x84, 0x21, 0x08, 0x8f, 0x71, 0x45, 0x59, 0x24,
	0x3d, 0x12, 0x45, 0x4c, 0x11, 0x6d, 0x1b, 0x74, 0x29, 0x64, 0x2c, 0xec, 0x42, 0x2c, 0x7e, 0xdc,
	0xeb, 0xdc, 0x45, 0xdf, 0x9f, 0xb0, 0x0b, 0x88, 0x8e, 0xe1, 0x49, 0x1f, 0xa4, 0xc2, 0x36, 0x5a,
	0xea, 0x4b, 0x10, 0x11, 0xe9, 0xc1, 0x9a, 0x55, 0xb1, 0xb6, 0xbe, 0x3b, 0x1e, 0xae, 0x63, 0x1f,
	0x27, 0x52, 0x0e, 0x98, 0x08, 0xd6, 0xe6, 0x12, 0x5f, 0xba, 0x76, 0x36, 0xd1, 0x8a, 0xc9, 0x23,
	0x39, 0x8b, 0x24, 0xe0, 0x22, 0xca, 0xa9, 0x78, 0xc3, 0x64, 0x49, 0x16, 0x4e, 0x11, 0xe1, 0x7b,
	0x54, 0xaa, 0x07, 0xfe, 0x39, 0xb4, 0x95, 0x34, 0xa4, 0xf5, 0xcf, 0x0b, 0x68, 0xb1, 0xa9, 0x0b,
	0x25, 0xf1, 0x00, 0xe5, 0xf7, 0x05, 0x10, 0x05, 0x78, 0xcb, 0x1d, 0x29, 0x72, 0x52, 0xc7, 0x61,
	0x19, 0x13, 0x88, 0x89, 0xb7, 0xff, 0x9c, 0x01, 0x99, 0xc8, 0x72, 0xd6, 0x5e, 0x7c, 0xfc, 0xf4,
	0x6a, 0x0e, 0x3b, 0x4b, 0xa6, 0x33, 0xb2, 0x91, 0x4f, 0x0c, 0xfc, 0xc6, 0x42, 0xf9, 0x87, 0x3c,
	0x98, 0xc6, 0x9c, 0x40, 0x66, 0x61, 0x4e, 0x91, 0x86, 0xb9, 0xa9, 0x99, 0xff, 0xab, 0x17, 0x53,
	0x66, 0xef, 0x79, 0x62, 0xb8, 0x34, 0xb8, 0x4a, 0x55, 0x9c, 0xae, 0xdb, 0xb7, 0xfa, 0xf1, 0x05,
	0x9a, 0x3f, 0x00, 0x85, 0x37, 0x6f, 0xe1, 0x3d, 0x00, 0x95, 0xca, 0xfb, 0x7d, 0x1a, 0xcc, 0x68,
	0xfb, 0x49, 0x6b, 0xfb, 0x11, 0xaf, 0x5c, 0x73, 0xd3, 0xe0, 0x0a, 0x73, 0xb4, 0x10, 0x77, 0x0b,
	0xd7, 0x6e, 0x49, 0x13, 0x03, 0x4c, 0xef, 0x52, 0xd6, 0x3f, 0xa6, 0xc0, 0x87, 0xb4, 0xab, 0x9a,
	0x16, 0xe1, 0x61, 0x33, 0xb0, 0x42, 0xf9, 0x26, 0x74, 0x61, 0x4a, 0x0f, 0x12, 0xc8, 0x2c, 0x3d,
	0x48, 0x91, 0xd9, 0x73, 0x56, 0xb3, 0xe7, 0xac, 0x7f, 0x98, 0x47, 0x8b, 0x2d, 0x7d, 0xfb, 0x24,
	0xf6, 0x93, 0x02, 0x97, 0x47, 0x93, 0x9a, 0x9b, 0x39, 0x52, 0xd8, 0xf5, 0x9b, 0xdc, 0x86, 0xa8,
	0xa4, 0x89, 0x7e, 0xc6, 0xc5, 0x0c, 0x91, 0xb9, 0xe2, 0xf8, 0xb5, 0x85, 0x0a, 0x47, 0x44, 0xb5,
	0x3b, 0x4d, 0x90, 0x54, 0x40, 0xd0, 0x52, 0xf1, 0xbf, 0xee, 0xaf, 0x09, 0x39, 0xc7, 0x50, 0xa9,
	0x80, 0xed, 0xd9, 0xc0, 0x46, 0x4e, 0x55, 0xcb, 0xd9, 0x70, 0x4a, 0x93, 0xe4, 0x78, 0x41, 0x12,
	0xd2, 0x58, 0x08, 0x88, 0x22, 0xf8, 0x9d, 0x85, 0xec, 0x96, 0x12, 0x40, 0x7a, 0xc7, 0xc0, 0x99,
	0x50, 0x26, 0xd7, 0x7e, 0x87, 0x44, 0x21, 0x48, 0xfc, 0xef, 0x04, 0xe2, 0x9b, 0xe1, 0xa9, 0xdc,
	0xdd, 0x6f, 0x8c, 0x32, 0xba, 0x37, 0xb5, 0xee, 0xdf, 0x70, 0x79, 0xa2, 0x6e, 0x61, 0x42, 0x77,
	0xac, 0xba, 0x8f, 0x16, 0xf7, 0xda, 0x6d, 0xd6, 0x8f, 0x14, 0x7e, 0x84, 0x72, 0x7a, 0x12, 0xe1,
	0x92, 0x9b, 0x1d, 0xd2, 0xee, 0xe8, 0xa0, 0xb3, 0xcb, 0x37, 0x78, 0x0d, 0x73, 0x41, 0x33, 0x2f,
	0x3b, 0x79, 0x4f, 0x0f, 0xae, 0x86, 0x55, 0xad, 0x3f, 0x43, 0x2b, 0xc9, 0xdc, 0x6a, 0x81, 0xd0,
	0x77, 0x91, 0xa2, 0xe5, 0x91, 0x61, 0x86, 0x9d, 0xaf, 0x33, 0x8e, 0x4f, 0x3a, 0x7b, 0x63, 0x14,
	0xa3, 0x47, 0x7a, 0x06, 0x34, 0x76, 0x2f, 0x58, 0xe2, 0xb9, 0xf3, 0xde, 0x7a, 0xb9, 0xf7, 0xd6,
	0xc2, 0x02, 0xfd, 0x72, 0x38, 0x8c, 0xaf, 0x1c, 0xb2, 0x93, 0xca, 0x51, 0x97, 0xa8, 0x33, 0x26,
	0x7a, 0xf8, 0xd7, 0xfd, 0x2e, 0xeb, 0x07, 0x95, 0xfb, 0x44, 0xd1, 0x4b, 0xc8, 0xb8, 0x9c, 0x5d,
	0x84, 0xae, 0xa3, 0x70, 0xb1, 0xa3, 0x14, 0x6f, 0x78, 0xde, 0x88, 0x10, 0xca, 0xec, 0xc2, 0x39,
	0x83, 0xff, 0x33, 0x5b, 0xf5, 0xdc, 0x8e, 0xbb, 0xe3, 0xfe, 0x6d, 0x17, 0xe2, 0xa3, 0x64, 0x3c,
	0x55, 0x6b, 0xae, 0xbe, 0x4a, 0x38, 0xef, 0xd2, 0xb6, 0x7e, 0x4b, 0xbc, 0x73, 0xc9, 0xa2, 0xc6,
	0xd8, 0xce, 0x69, 0x4e, 0xbf, 0x9a, 0x7e, 0x5e, 0xbf, 0x34, 0xff, 0x7c, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x8e, 0x46, 0x5f, 0xd1, 0x53, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DevicesClient is the client API for Devices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DevicesClient interface {
	Create(ctx context.Context, in *registrypb.CreateRequest, opts ...grpc.CallOption) (*registrypb.CreateResponse, error)
	Update(ctx context.Context, in *registrypb.UpdateRequest, opts ...grpc.CallOption) (*registrypb.UpdateResponse, error)
	Get(ctx context.Context, in *registrypb.GetRequest, opts ...grpc.CallOption) (*registrypb.GetResponse, error)
	List(ctx context.Context, in *registrypb.ListDevicesRequest, opts ...grpc.CallOption) (*registrypb.ListResponse, error)
	Delete(ctx context.Context, in *registrypb.DeleteRequest, opts ...grpc.CallOption) (*registrypb.DeleteResponse, error)
}

type devicesClient struct {
	cc *grpc.ClientConn
}

func NewDevicesClient(cc *grpc.ClientConn) DevicesClient {
	return &devicesClient{cc}
}

func (c *devicesClient) Create(ctx context.Context, in *registrypb.CreateRequest, opts ...grpc.CallOption) (*registrypb.CreateResponse, error) {
	out := new(registrypb.CreateResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Devices/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) Update(ctx context.Context, in *registrypb.UpdateRequest, opts ...grpc.CallOption) (*registrypb.UpdateResponse, error) {
	out := new(registrypb.UpdateResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Devices/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) Get(ctx context.Context, in *registrypb.GetRequest, opts ...grpc.CallOption) (*registrypb.GetResponse, error) {
	out := new(registrypb.GetResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Devices/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) List(ctx context.Context, in *registrypb.ListDevicesRequest, opts ...grpc.CallOption) (*registrypb.ListResponse, error) {
	out := new(registrypb.ListResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Devices/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) Delete(ctx context.Context, in *registrypb.DeleteRequest, opts ...grpc.CallOption) (*registrypb.DeleteResponse, error) {
	out := new(registrypb.DeleteResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Devices/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevicesServer is the server API for Devices service.
type DevicesServer interface {
	Create(context.Context, *registrypb.CreateRequest) (*registrypb.CreateResponse, error)
	Update(context.Context, *registrypb.UpdateRequest) (*registrypb.UpdateResponse, error)
	Get(context.Context, *registrypb.GetRequest) (*registrypb.GetResponse, error)
	List(context.Context, *registrypb.ListDevicesRequest) (*registrypb.ListResponse, error)
	Delete(context.Context, *registrypb.DeleteRequest) (*registrypb.DeleteResponse, error)
}

func RegisterDevicesServer(s *grpc.Server, srv DevicesServer) {
	s.RegisterService(&_Devices_serviceDesc, srv)
}

func _Devices_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(registrypb.CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Devices/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).Create(ctx, req.(*registrypb.CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(registrypb.UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Devices/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).Update(ctx, req.(*registrypb.UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(registrypb.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Devices/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).Get(ctx, req.(*registrypb.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(registrypb.ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Devices/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).List(ctx, req.(*registrypb.ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(registrypb.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Devices/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).Delete(ctx, req.(*registrypb.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Devices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.api.Devices",
	HandlerType: (*DevicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Devices_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Devices_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Devices_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Devices_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Devices_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apiserver/apipb/api.proto",
}

// ShadowsClient is the client API for Shadows service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShadowsClient interface {
	Get(ctx context.Context, in *shadowpb.GetRequest, opts ...grpc.CallOption) (*shadowpb.GetResponse, error)
	PatchDesiredState(ctx context.Context, in *shadowpb.PatchDesiredStateRequest, opts ...grpc.CallOption) (*shadowpb.PatchDesiredStateResponse, error)
	StreamReportedStateChanges(ctx context.Context, in *shadowpb.StreamReportedStateChangesRequest, opts ...grpc.CallOption) (Shadows_StreamReportedStateChangesClient, error)
}

type shadowsClient struct {
	cc *grpc.ClientConn
}

func NewShadowsClient(cc *grpc.ClientConn) ShadowsClient {
	return &shadowsClient{cc}
}

func (c *shadowsClient) Get(ctx context.Context, in *shadowpb.GetRequest, opts ...grpc.CallOption) (*shadowpb.GetResponse, error) {
	out := new(shadowpb.GetResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Shadows/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shadowsClient) PatchDesiredState(ctx context.Context, in *shadowpb.PatchDesiredStateRequest, opts ...grpc.CallOption) (*shadowpb.PatchDesiredStateResponse, error) {
	out := new(shadowpb.PatchDesiredStateResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Shadows/PatchDesiredState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shadowsClient) StreamReportedStateChanges(ctx context.Context, in *shadowpb.StreamReportedStateChangesRequest, opts ...grpc.CallOption) (Shadows_StreamReportedStateChangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Shadows_serviceDesc.Streams[0], "/infinimesh.api.Shadows/StreamReportedStateChanges", opts...)
	if err != nil {
		return nil, err
	}
	x := &shadowsStreamReportedStateChangesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Shadows_StreamReportedStateChangesClient interface {
	Recv() (*shadowpb.StreamReportedStateChangesResponse, error)
	grpc.ClientStream
}

type shadowsStreamReportedStateChangesClient struct {
	grpc.ClientStream
}

func (x *shadowsStreamReportedStateChangesClient) Recv() (*shadowpb.StreamReportedStateChangesResponse, error) {
	m := new(shadowpb.StreamReportedStateChangesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ShadowsServer is the server API for Shadows service.
type ShadowsServer interface {
	Get(context.Context, *shadowpb.GetRequest) (*shadowpb.GetResponse, error)
	PatchDesiredState(context.Context, *shadowpb.PatchDesiredStateRequest) (*shadowpb.PatchDesiredStateResponse, error)
	StreamReportedStateChanges(*shadowpb.StreamReportedStateChangesRequest, Shadows_StreamReportedStateChangesServer) error
}

func RegisterShadowsServer(s *grpc.Server, srv ShadowsServer) {
	s.RegisterService(&_Shadows_serviceDesc, srv)
}

func _Shadows_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(shadowpb.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShadowsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Shadows/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShadowsServer).Get(ctx, req.(*shadowpb.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shadows_PatchDesiredState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(shadowpb.PatchDesiredStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShadowsServer).PatchDesiredState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Shadows/PatchDesiredState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShadowsServer).PatchDesiredState(ctx, req.(*shadowpb.PatchDesiredStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shadows_StreamReportedStateChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(shadowpb.StreamReportedStateChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShadowsServer).StreamReportedStateChanges(m, &shadowsStreamReportedStateChangesServer{stream})
}

type Shadows_StreamReportedStateChangesServer interface {
	Send(*shadowpb.StreamReportedStateChangesResponse) error
	grpc.ServerStream
}

type shadowsStreamReportedStateChangesServer struct {
	grpc.ServerStream
}

func (x *shadowsStreamReportedStateChangesServer) Send(m *shadowpb.StreamReportedStateChangesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Shadows_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.api.Shadows",
	HandlerType: (*ShadowsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Shadows_Get_Handler,
		},
		{
			MethodName: "PatchDesiredState",
			Handler:    _Shadows_PatchDesiredState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamReportedStateChanges",
			Handler:       _Shadows_StreamReportedStateChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/apiserver/apipb/api.proto",
}

// AccountClient is the client API for Account service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountClient interface {
	Token(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
}

type accountClient struct {
	cc *grpc.ClientConn
}

func NewAccountClient(cc *grpc.ClientConn) AccountClient {
	return &accountClient{cc}
}

func (c *accountClient) Token(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Account/Token", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServer is the server API for Account service.
type AccountServer interface {
	Token(context.Context, *TokenRequest) (*TokenResponse, error)
}

func RegisterAccountServer(s *grpc.Server, srv AccountServer) {
	s.RegisterService(&_Account_serviceDesc, srv)
}

func _Account_Token_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServer).Token(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Account/Token",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServer).Token(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Account_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.api.Account",
	HandlerType: (*AccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Token",
			Handler:    _Account_Token_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apiserver/apipb/api.proto",
}

// ObjectServiceClient is the client API for ObjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ObjectServiceClient interface {
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*nodepb.ListObjectsResponse, error)
}

type objectServiceClient struct {
	cc *grpc.ClientConn
}

func NewObjectServiceClient(cc *grpc.ClientConn) ObjectServiceClient {
	return &objectServiceClient{cc}
}

func (c *objectServiceClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*nodepb.ListObjectsResponse, error) {
	out := new(nodepb.ListObjectsResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.ObjectService/ListObjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectServiceServer is the server API for ObjectService service.
type ObjectServiceServer interface {
	ListObjects(context.Context, *ListObjectsRequest) (*nodepb.ListObjectsResponse, error)
}

func RegisterObjectServiceServer(s *grpc.Server, srv ObjectServiceServer) {
	s.RegisterService(&_ObjectService_serviceDesc, srv)
}

func _ObjectService_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectServiceServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.ObjectService/ListObjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectServiceServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ObjectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.api.ObjectService",
	HandlerType: (*ObjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListObjects",
			Handler:    _ObjectService_ListObjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apiserver/apipb/api.proto",
}
