// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apiserver/apipb/api.proto

package apipb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	nodepb "github.com/infinimesh/infinimesh/pkg/node/nodepb"
	registrypb "github.com/infinimesh/infinimesh/pkg/registry/registrypb"
	shadowpb "github.com/infinimesh/infinimesh/pkg/shadow/shadowpb"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TokenRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a22a27722afd30, []int{0}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *TokenRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type TokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a22a27722afd30, []int{1}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

func (m *TokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ListDevicesRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDevicesRequest) Reset()         { *m = ListDevicesRequest{} }
func (m *ListDevicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListDevicesRequest) ProtoMessage()    {}
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a22a27722afd30, []int{2}
}

func (m *ListDevicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDevicesRequest.Unmarshal(m, b)
}
func (m *ListDevicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDevicesRequest.Marshal(b, m, deterministic)
}
func (m *ListDevicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDevicesRequest.Merge(m, src)
}
func (m *ListDevicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListDevicesRequest.Size(m)
}
func (m *ListDevicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDevicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDevicesRequest proto.InternalMessageInfo

func (m *ListDevicesRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type ListObjectsRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Recurse              bool     `protobuf:"varint,2,opt,name=recurse,proto3" json:"recurse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListObjectsRequest) Reset()         { *m = ListObjectsRequest{} }
func (m *ListObjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListObjectsRequest) ProtoMessage()    {}
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a22a27722afd30, []int{3}
}

func (m *ListObjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListObjectsRequest.Unmarshal(m, b)
}
func (m *ListObjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListObjectsRequest.Marshal(b, m, deterministic)
}
func (m *ListObjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListObjectsRequest.Merge(m, src)
}
func (m *ListObjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListObjectsRequest.Size(m)
}
func (m *ListObjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListObjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListObjectsRequest proto.InternalMessageInfo

func (m *ListObjectsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *ListObjectsRequest) GetRecurse() bool {
	if m != nil {
		return m.Recurse
	}
	return false
}

type CreateObjectRequest struct {
	Parent               *wrappers.StringValue `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Namespace            string                `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Object               *nodepb.Object        `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateObjectRequest) Reset()         { *m = CreateObjectRequest{} }
func (m *CreateObjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateObjectRequest) ProtoMessage()    {}
func (*CreateObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a22a27722afd30, []int{4}
}

func (m *CreateObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateObjectRequest.Unmarshal(m, b)
}
func (m *CreateObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateObjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateObjectRequest.Merge(m, src)
}
func (m *CreateObjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateObjectRequest.Size(m)
}
func (m *CreateObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateObjectRequest proto.InternalMessageInfo

func (m *CreateObjectRequest) GetParent() *wrappers.StringValue {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *CreateObjectRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateObjectRequest) GetObject() *nodepb.Object {
	if m != nil {
		return m.Object
	}
	return nil
}

type CreateNamespacePermissionRequest struct {
	AccountId            string      `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Namespace            string      `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Permission           *Permission `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateNamespacePermissionRequest) Reset()         { *m = CreateNamespacePermissionRequest{} }
func (m *CreateNamespacePermissionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNamespacePermissionRequest) ProtoMessage()    {}
func (*CreateNamespacePermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a22a27722afd30, []int{5}
}

func (m *CreateNamespacePermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespacePermissionRequest.Unmarshal(m, b)
}
func (m *CreateNamespacePermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespacePermissionRequest.Marshal(b, m, deterministic)
}
func (m *CreateNamespacePermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespacePermissionRequest.Merge(m, src)
}
func (m *CreateNamespacePermissionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNamespacePermissionRequest.Size(m)
}
func (m *CreateNamespacePermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespacePermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespacePermissionRequest proto.InternalMessageInfo

func (m *CreateNamespacePermissionRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *CreateNamespacePermissionRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *CreateNamespacePermissionRequest) GetPermission() *Permission {
	if m != nil {
		return m.Permission
	}
	return nil
}

// Permission.Action may either be NONE, READ or WRITE.
type Permission struct {
	Action               nodepb.Action `protobuf:"varint,3,opt,name=action,proto3,enum=infinimesh.node.Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a22a27722afd30, []int{6}
}

func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetAction() nodepb.Action {
	if m != nil {
		return m.Action
	}
	return nodepb.Action_NONE
}

type CreateNamespacePermissionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNamespacePermissionResponse) Reset()         { *m = CreateNamespacePermissionResponse{} }
func (m *CreateNamespacePermissionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNamespacePermissionResponse) ProtoMessage()    {}
func (*CreateNamespacePermissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_06a22a27722afd30, []int{7}
}

func (m *CreateNamespacePermissionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNamespacePermissionResponse.Unmarshal(m, b)
}
func (m *CreateNamespacePermissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNamespacePermissionResponse.Marshal(b, m, deterministic)
}
func (m *CreateNamespacePermissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNamespacePermissionResponse.Merge(m, src)
}
func (m *CreateNamespacePermissionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNamespacePermissionResponse.Size(m)
}
func (m *CreateNamespacePermissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNamespacePermissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNamespacePermissionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TokenRequest)(nil), "infinimesh.api.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "infinimesh.api.TokenResponse")
	proto.RegisterType((*ListDevicesRequest)(nil), "infinimesh.api.ListDevicesRequest")
	proto.RegisterType((*ListObjectsRequest)(nil), "infinimesh.api.ListObjectsRequest")
	proto.RegisterType((*CreateObjectRequest)(nil), "infinimesh.api.CreateObjectRequest")
	proto.RegisterType((*CreateNamespacePermissionRequest)(nil), "infinimesh.api.CreateNamespacePermissionRequest")
	proto.RegisterType((*Permission)(nil), "infinimesh.api.Permission")
	proto.RegisterType((*CreateNamespacePermissionResponse)(nil), "infinimesh.api.CreateNamespacePermissionResponse")
}

func init() { proto.RegisterFile("pkg/apiserver/apipb/api.proto", fileDescriptor_06a22a27722afd30) }

var fileDescriptor_06a22a27722afd30 = []byte{
	// 1285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0x41, 0x53, 0xdb, 0x46,
	0x14, 0x1e, 0x91, 0xd8, 0x90, 0x07, 0x38, 0xb0, 0x90, 0x40, 0x14, 0x48, 0x1d, 0x25, 0x24, 0x84,
	0x24, 0x12, 0x51, 0x93, 0x8b, 0x67, 0xda, 0x29, 0x81, 0x96, 0x61, 0x26, 0x93, 0x52, 0x93, 0xf4,
	0xd0, 0x0b, 0xb3, 0xb6, 0x16, 0x23, 0xb0, 0xb5, 0x8a, 0x76, 0x0d, 0x93, 0x32, 0xcc, 0x74, 0xda,
	0x5f, 0x90, 0xf6, 0xd6, 0xfe, 0x87, 0x76, 0x7a, 0xee, 0xf4, 0x1f, 0xb4, 0xa7, 0x9e, 0x7a, 0xef,
	0x0f, 0xe9, 0xec, 0x6a, 0x57, 0x96, 0x2c, 0x19, 0x9b, 0x8b, 0xb5, 0xd2, 0xfb, 0xf6, 0x7d, 0xdf,
	0x7b, 0xbb, 0xfb, 0xf6, 0x19, 0x96, 0xc3, 0xe3, 0x96, 0x83, 0x43, 0x9f, 0x91, 0xe8, 0x84, 0x44,
	0x62, 0x14, 0x36, 0xc4, 0xaf, 0x1d, 0x46, 0x94, 0x53, 0x54, 0xf1, 0x83, 0x03, 0x3f, 0xf0, 0x3b,
	0x84, 0x1d, 0xda, 0x38, 0xf4, 0xcd, 0xa5, 0x16, 0xa5, 0xad, 0x36, 0x11, 0x08, 0x07, 0x07, 0x01,
	0xe5, 0x98, 0xfb, 0x34, 0x60, 0x31, 0xda, 0xbc, 0xa3, 0xac, 0xf2, 0xad, 0xd1, 0x3d, 0x70, 0x4e,
	0x23, 0x1c, 0x86, 0x24, 0xd2, 0xf6, 0xdb, 0xfd, 0x76, 0xd2, 0x09, 0xf9, 0x7b, 0x65, 0x34, 0x85,
	0x92, 0x80, 0x7a, 0x44, 0xfe, 0x84, 0x0d, 0xf9, 0x50, 0xb6, 0xa7, 0xc2, 0x16, 0x91, 0x96, 0xcf,
	0x78, 0xf4, 0x3e, 0x19, 0x84, 0x0d, 0xc7, 0x23, 0x27, 0x7e, 0x93, 0xec, 0xeb, 0x2f, 0x0a, 0x5e,
	0x15, 0x70, 0x76, 0x88, 0x3d, 0x7a, 0xaa, 0x1e, 0x61, 0x43, 0x0d, 0x14, 0xe2, 0x89, 0x7c, 0x34,
	0x9f, 0xb6, 0x48, 0xf0, 0x94, 0x9d, 0xe2, 0x56, 0x8b, 0x44, 0x0e, 0x0d, 0x65, 0x2c, 0xf9, 0xb8,
	0xac, 0x2f, 0x60, 0xea, 0x0d, 0x3d, 0x26, 0x41, 0x9d, 0xbc, 0xeb, 0x12, 0xc6, 0x91, 0x09, 0x13,
	0x5d, 0x46, 0xa2, 0x00, 0x77, 0xc8, 0xa2, 0x51, 0x35, 0x56, 0xaf, 0xd5, 0x93, 0x77, 0x61, 0x0b,
	0x31, 0x63, 0xa7, 0x34, 0xf2, 0x16, 0xc7, 0x62, 0x9b, 0x7e, 0xb7, 0x56, 0x60, 0x5a, 0xf9, 0x61,
	0x21, 0x0d, 0x18, 0x41, 0xf3, 0x50, 0xe2, 0xe2, 0x83, 0xf2, 0x12, 0xbf, 0x58, 0x2e, 0xa0, 0x57,
	0x3e, 0xe3, 0x5b, 0x32, 0x36, 0xa6, 0x49, 0x97, 0xe0, 0x9a, 0x20, 0x60, 0x21, 0x6e, 0x6a, 0xd6,
	0xde, 0x07, 0xeb, 0x55, 0x3c, 0xe7, 0xcb, 0xc6, 0x11, 0x69, 0xf2, 0xd1, 0xe6, 0xa0, 0x45, 0x18,
	0x8f, 0x48, 0xb3, 0x1b, 0x31, 0x22, 0x95, 0x4e, 0xd4, 0xf5, 0xab, 0xf5, 0xb3, 0x01, 0x73, 0x9b,
	0x11, 0xc1, 0x9c, 0xc4, 0x0e, 0xb5, 0xbf, 0xe7, 0x50, 0x0e, 0x71, 0x44, 0x02, 0x2e, 0x9d, 0x4d,
	0xba, 0x4b, 0x76, 0xbc, 0xa2, 0xb6, 0x5e, 0x51, 0x7b, 0x8f, 0x47, 0x7e, 0xd0, 0xfa, 0x1a, 0xb7,
	0xbb, 0xa4, 0xae, 0xb0, 0x59, 0x15, 0x63, 0xfd, 0x2a, 0x1c, 0x28, 0x53, 0x49, 0xb2, 0x78, 0x45,
	0xfa, 0x5c, 0xb0, 0x53, 0x7b, 0x4e, 0xee, 0x01, 0xa5, 0x41, 0xc1, 0xac, 0x5f, 0x0c, 0xa8, 0xc6,
	0xe2, 0x5e, 0x6b, 0x27, 0xbb, 0x24, 0xea, 0xf8, 0x8c, 0xf9, 0x34, 0x59, 0xa2, 0x65, 0x00, 0xdc,
	0x6c, 0xd2, 0x6e, 0xc0, 0xf7, 0x7d, 0x4f, 0x87, 0xae, 0xbe, 0xec, 0x78, 0x43, 0x24, 0xd5, 0x00,
	0xc2, 0xc4, 0xa3, 0x92, 0x65, 0xda, 0xd9, 0xa3, 0x60, 0xa7, 0x38, 0x53, 0x68, 0xeb, 0x13, 0x80,
	0x9e, 0x45, 0x04, 0x87, 0x9b, 0x5c, 0x7b, 0xa9, 0x14, 0x04, 0xb7, 0x21, 0xcd, 0x75, 0x05, 0xb3,
	0xee, 0xc1, 0xdd, 0x0b, 0x62, 0x8b, 0xb7, 0x8d, 0xfb, 0xf7, 0x55, 0x18, 0x57, 0xbb, 0x03, 0x45,
	0x50, 0x8e, 0x27, 0xa0, 0xd5, 0xb4, 0xef, 0xf8, 0x60, 0x24, 0xe7, 0x22, 0x86, 0xa8, 0xe4, 0x98,
	0x8f, 0x46, 0x40, 0xc6, 0x54, 0xd6, 0xdc, 0xf7, 0xff, 0xfc, 0xf7, 0xd3, 0xd8, 0xb4, 0x35, 0xa1,
	0x8e, 0x1a, 0xab, 0x19, 0x6b, 0xe8, 0x07, 0x03, 0xca, 0x6f, 0x43, 0x6f, 0x18, 0x69, 0x0c, 0x19,
	0x85, 0x54, 0x23, 0x15, 0xe9, 0x7d, 0x49, 0x7a, 0xc7, 0x9d, 0xd7, 0xa4, 0xce, 0x59, 0x3c, 0xb0,
	0x7d, 0xef, 0xbc, 0x56, 0x8e, 0xc7, 0xe8, 0x18, 0xae, 0x6c, 0x13, 0x8e, 0x56, 0x2e, 0xf0, 0xbb,
	0x4d, 0xf4, 0xd6, 0x35, 0x1f, 0x0c, 0x83, 0x29, 0xee, 0x1b, 0x92, 0xfb, 0x3a, 0x9a, 0xee, 0x71,
	0xfb, 0xde, 0x39, 0x22, 0x70, 0x55, 0x9c, 0x2f, 0x64, 0xf5, 0x6f, 0x83, 0xfc, 0x49, 0x35, 0x1f,
	0x5e, 0x40, 0x25, 0xe0, 0x09, 0xd7, 0x8c, 0xe4, 0x02, 0x94, 0x24, 0x17, 0x71, 0x28, 0x6f, 0x91,
	0x36, 0x19, 0x92, 0xd8, 0x18, 0x32, 0x4a, 0x62, 0x35, 0x32, 0x1b, 0xdc, 0x5a, 0x36, 0x38, 0xf7,
	0xf7, 0x2b, 0x50, 0xde, 0xe3, 0x98, 0x13, 0x86, 0x70, 0x9c, 0xd4, 0xe5, 0xb4, 0x4f, 0x55, 0x39,
	0x53, 0xc9, 0xbc, 0x33, 0xc8, 0xac, 0x78, 0x6e, 0x4b, 0x9e, 0x1b, 0x68, 0x2e, 0xc3, 0xe3, 0x30,
	0xc1, 0x81, 0x3e, 0x18, 0x30, 0xbb, 0x8b, 0x79, 0xf3, 0x70, 0x8b, 0x30, 0x3f, 0x22, 0x9e, 0x64,
	0x46, 0x8f, 0x0b, 0x5c, 0xe6, 0x50, 0x9a, 0xff, 0xc9, 0x68, 0x60, 0xa5, 0xe6, 0xae, 0x54, 0x73,
	0xdb, 0x2d, 0x52, 0x53, 0xbb, 0xea, 0x61, 0x8e, 0xd1, 0x6f, 0x06, 0x98, 0x7b, 0x3c, 0x22, 0xb8,
	0x53, 0x27, 0x21, 0x8d, 0xb8, 0x72, 0xb1, 0x79, 0x88, 0x83, 0x16, 0x61, 0xe8, 0x79, 0x01, 0xdf,
	0x60, 0xb8, 0x56, 0xf9, 0xe2, 0x92, 0xb3, 0x94, 0x5c, 0x4b, 0xca, 0x5d, 0x42, 0x66, 0x81, 0x5c,
	0x87, 0xc9, 0xf9, 0xeb, 0x86, 0xfb, 0xa1, 0x04, 0x13, 0x1b, 0x71, 0x3d, 0x63, 0xe8, 0x2b, 0x98,
	0xdc, 0x23, 0xed, 0x03, 0xf5, 0x8e, 0x6e, 0xe6, 0xca, 0xf2, 0xe7, 0xe2, 0xa2, 0x35, 0x17, 0x0b,
	0xaa, 0x8f, 0x9c, 0x91, 0xda, 0x89, 0xaa, 0x46, 0xa2, 0x7d, 0x28, 0xc9, 0xbb, 0x0a, 0x2d, 0xf5,
	0xef, 0xf8, 0xf4, 0x55, 0x68, 0x2e, 0x0f, 0xb0, 0xaa, 0x58, 0x6e, 0x49, 0xbf, 0x73, 0x56, 0x45,
	0xfb, 0x75, 0xe4, 0x15, 0x27, 0x8a, 0xc8, 0x77, 0x06, 0xcc, 0xc6, 0xc5, 0xe6, 0x2d, 0x23, 0x91,
	0x96, 0xfe, 0x28, 0x27, 0x31, 0x87, 0xd1, 0xd4, 0x6b, 0xa3, 0x40, 0x95, 0x8e, 0x79, 0xa9, 0xa3,
	0x62, 0x5d, 0xd3, 0x3a, 0x64, 0x1d, 0x6b, 0x00, 0x6c, 0x13, 0xae, 0xa9, 0xad, 0x9c, 0xbf, 0x9e,
	0x51, 0x73, 0x0e, 0xce, 0xe0, 0x4d, 0xc9, 0x30, 0x83, 0x92, 0x48, 0x55, 0xe1, 0xf8, 0x16, 0xa6,
	0xe3, 0xea, 0xa6, 0x69, 0x56, 0x72, 0x2e, 0x32, 0xf6, 0xe1, 0x4c, 0xab, 0x92, 0xc9, 0x72, 0x17,
	0x52, 0x4c, 0x6a, 0x64, 0x77, 0x45, 0x81, 0x1c, 0xd7, 0x6b, 0x18, 0xc0, 0x94, 0xa8, 0x37, 0xc9,
	0x36, 0xb9, 0x9f, 0xf3, 0x99, 0x36, 0x6b, 0xe6, 0x95, 0x21, 0x28, 0x95, 0xd2, 0x59, 0x29, 0x63,
	0x12, 0xf5, 0x52, 0xea, 0xfe, 0x35, 0x06, 0xe3, 0xaa, 0x03, 0x41, 0x3e, 0x4c, 0xa6, 0x1a, 0x92,
	0xe2, 0xba, 0x99, 0xed, 0x56, 0xcc, 0x62, 0x79, 0x09, 0x28, 0x57, 0x34, 0xa9, 0xf2, 0x8d, 0x61,
	0x2a, 0xdd, 0xac, 0xa0, 0x7b, 0xfd, 0x5c, 0x05, 0xad, 0x8c, 0x39, 0xa8, 0xcd, 0x48, 0xdd, 0x78,
	0xca, 0xbf, 0xd8, 0x29, 0x0c, 0xa6, 0xe2, 0x52, 0xaa, 0x28, 0xf2, 0x52, 0xd3, 0xe6, 0xc1, 0x99,
	0xcc, 0xa2, 0x54, 0x44, 0x6a, 0xeb, 0xac, 0x55, 0x34, 0xa3, 0x73, 0x26, 0xd6, 0xd1, 0xfd, 0xa3,
	0x04, 0x90, 0xb4, 0x01, 0x0c, 0x05, 0x70, 0xbd, 0xaf, 0x35, 0x40, 0x0f, 0x07, 0x1c, 0x81, 0x04,
	0xa1, 0x95, 0x98, 0x39, 0x60, 0x02, 0xd1, 0xf4, 0xd6, 0xa4, 0x93, 0x74, 0x40, 0x32, 0xe6, 0x77,
	0x30, 0xb5, 0x4d, 0x78, 0x8f, 0xec, 0x7e, 0xd1, 0xf9, 0xb8, 0x14, 0xd3, 0x47, 0x92, 0xe9, 0x16,
	0x5a, 0x48, 0x31, 0x39, 0x67, 0xc9, 0xf8, 0x1c, 0x9d, 0x40, 0x45, 0x2c, 0x79, 0x2a, 0xe8, 0x07,
	0x85, 0x7b, 0xa2, 0x07, 0x28, 0xbc, 0x73, 0x0b, 0x71, 0xd9, 0x86, 0x06, 0xa5, 0xa3, 0x45, 0x7f,
	0x1a, 0x30, 0x13, 0x67, 0x2e, 0xd5, 0xbb, 0xad, 0x17, 0x6f, 0xa3, 0xc1, 0x4d, 0xa7, 0xf9, 0xec,
	0x12, 0x33, 0x94, 0x9c, 0x2d, 0x29, 0xe7, 0x53, 0x73, 0x7d, 0x40, 0x4a, 0x9c, 0x5e, 0x6b, 0xd9,
	0x3b, 0xe6, 0xfb, 0xe2, 0x94, 0xa7, 0x9a, 0x4e, 0x71, 0xa5, 0x5e, 0x17, 0xf1, 0xf6, 0x08, 0x18,
	0x2a, 0xce, 0x48, 0x0a, 0xa1, 0x55, 0xaf, 0x0e, 0x07, 0x2a, 0xb1, 0x8f, 0xa5, 0xd8, 0x15, 0x74,
	0x6f, 0x04, 0xb1, 0x2f, 0xff, 0x35, 0x7e, 0xdc, 0xf8, 0xd5, 0x40, 0x11, 0x2c, 0xec, 0x24, 0xee,
	0xab, 0x3b, 0xf4, 0x4d, 0x75, 0xb7, 0x8d, 0xf9, 0x01, 0x8d, 0x3a, 0xe8, 0xd6, 0x66, 0x9b, 0x76,
	0xbd, 0xea, 0x6b, 0xcc, 0xfd, 0x13, 0x92, 0x31, 0x59, 0x2f, 0x00, 0x7a, 0xb3, 0xd0, 0xfc, 0x21,
	0xe7, 0x61, 0xcd, 0x71, 0x52, 0x3a, 0x7d, 0x6a, 0xce, 0x1e, 0x51, 0xf2, 0x59, 0xe6, 0x93, 0x5b,
	0x5a, 0xb7, 0xd7, 0xed, 0x67, 0xe6, 0xac, 0xc8, 0x7d, 0xc6, 0xb2, 0x66, 0x8c, 0xb9, 0x33, 0x38,
	0x0c, 0xdb, 0x7e, 0x53, 0xfe, 0xb3, 0x73, 0x8e, 0x18, 0x0d, 0x6a, 0xb9, 0x2f, 0x80, 0x9a, 0xb4,
	0xd3, 0xb7, 0x88, 0x2f, 0x27, 0x36, 0x42, 0x7f, 0x57, 0x5c, 0xa4, 0xbb, 0xc6, 0x37, 0x25, 0xf9,
	0x07, 0xb9, 0x51, 0x96, 0x17, 0xeb, 0xc7, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x6c, 0x53,
	0x80, 0x3e, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DevicesClient is the client API for Devices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DevicesClient interface {
	Create(ctx context.Context, in *registrypb.CreateRequest, opts ...grpc.CallOption) (*registrypb.CreateResponse, error)
	Update(ctx context.Context, in *registrypb.UpdateRequest, opts ...grpc.CallOption) (*registrypb.UpdateResponse, error)
	Get(ctx context.Context, in *registrypb.GetRequest, opts ...grpc.CallOption) (*registrypb.GetResponse, error)
	List(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*registrypb.ListResponse, error)
	Delete(ctx context.Context, in *registrypb.DeleteRequest, opts ...grpc.CallOption) (*registrypb.DeleteResponse, error)
}

type devicesClient struct {
	cc *grpc.ClientConn
}

func NewDevicesClient(cc *grpc.ClientConn) DevicesClient {
	return &devicesClient{cc}
}

func (c *devicesClient) Create(ctx context.Context, in *registrypb.CreateRequest, opts ...grpc.CallOption) (*registrypb.CreateResponse, error) {
	out := new(registrypb.CreateResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Devices/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) Update(ctx context.Context, in *registrypb.UpdateRequest, opts ...grpc.CallOption) (*registrypb.UpdateResponse, error) {
	out := new(registrypb.UpdateResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Devices/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) Get(ctx context.Context, in *registrypb.GetRequest, opts ...grpc.CallOption) (*registrypb.GetResponse, error) {
	out := new(registrypb.GetResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Devices/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) List(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*registrypb.ListResponse, error) {
	out := new(registrypb.ListResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Devices/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) Delete(ctx context.Context, in *registrypb.DeleteRequest, opts ...grpc.CallOption) (*registrypb.DeleteResponse, error) {
	out := new(registrypb.DeleteResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Devices/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevicesServer is the server API for Devices service.
type DevicesServer interface {
	Create(context.Context, *registrypb.CreateRequest) (*registrypb.CreateResponse, error)
	Update(context.Context, *registrypb.UpdateRequest) (*registrypb.UpdateResponse, error)
	Get(context.Context, *registrypb.GetRequest) (*registrypb.GetResponse, error)
	List(context.Context, *ListDevicesRequest) (*registrypb.ListResponse, error)
	Delete(context.Context, *registrypb.DeleteRequest) (*registrypb.DeleteResponse, error)
}

func RegisterDevicesServer(s *grpc.Server, srv DevicesServer) {
	s.RegisterService(&_Devices_serviceDesc, srv)
}

func _Devices_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(registrypb.CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Devices/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).Create(ctx, req.(*registrypb.CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(registrypb.UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Devices/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).Update(ctx, req.(*registrypb.UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(registrypb.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Devices/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).Get(ctx, req.(*registrypb.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Devices/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).List(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(registrypb.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Devices/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).Delete(ctx, req.(*registrypb.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Devices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.api.Devices",
	HandlerType: (*DevicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Devices_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Devices_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Devices_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Devices_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Devices_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apiserver/apipb/api.proto",
}

// StatesClient is the client API for States service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatesClient interface {
	Get(ctx context.Context, in *shadowpb.GetRequest, opts ...grpc.CallOption) (*shadowpb.GetResponse, error)
	PatchDesiredState(ctx context.Context, in *shadowpb.PatchDesiredStateRequest, opts ...grpc.CallOption) (*shadowpb.PatchDesiredStateResponse, error)
	StreamReportedStateChanges(ctx context.Context, in *shadowpb.StreamReportedStateChangesRequest, opts ...grpc.CallOption) (States_StreamReportedStateChangesClient, error)
}

type statesClient struct {
	cc *grpc.ClientConn
}

func NewStatesClient(cc *grpc.ClientConn) StatesClient {
	return &statesClient{cc}
}

func (c *statesClient) Get(ctx context.Context, in *shadowpb.GetRequest, opts ...grpc.CallOption) (*shadowpb.GetResponse, error) {
	out := new(shadowpb.GetResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.States/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statesClient) PatchDesiredState(ctx context.Context, in *shadowpb.PatchDesiredStateRequest, opts ...grpc.CallOption) (*shadowpb.PatchDesiredStateResponse, error) {
	out := new(shadowpb.PatchDesiredStateResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.States/PatchDesiredState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statesClient) StreamReportedStateChanges(ctx context.Context, in *shadowpb.StreamReportedStateChangesRequest, opts ...grpc.CallOption) (States_StreamReportedStateChangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_States_serviceDesc.Streams[0], "/infinimesh.api.States/StreamReportedStateChanges", opts...)
	if err != nil {
		return nil, err
	}
	x := &statesStreamReportedStateChangesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type States_StreamReportedStateChangesClient interface {
	Recv() (*shadowpb.StreamReportedStateChangesResponse, error)
	grpc.ClientStream
}

type statesStreamReportedStateChangesClient struct {
	grpc.ClientStream
}

func (x *statesStreamReportedStateChangesClient) Recv() (*shadowpb.StreamReportedStateChangesResponse, error) {
	m := new(shadowpb.StreamReportedStateChangesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StatesServer is the server API for States service.
type StatesServer interface {
	Get(context.Context, *shadowpb.GetRequest) (*shadowpb.GetResponse, error)
	PatchDesiredState(context.Context, *shadowpb.PatchDesiredStateRequest) (*shadowpb.PatchDesiredStateResponse, error)
	StreamReportedStateChanges(*shadowpb.StreamReportedStateChangesRequest, States_StreamReportedStateChangesServer) error
}

func RegisterStatesServer(s *grpc.Server, srv StatesServer) {
	s.RegisterService(&_States_serviceDesc, srv)
}

func _States_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(shadowpb.GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.States/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatesServer).Get(ctx, req.(*shadowpb.GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _States_PatchDesiredState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(shadowpb.PatchDesiredStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatesServer).PatchDesiredState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.States/PatchDesiredState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatesServer).PatchDesiredState(ctx, req.(*shadowpb.PatchDesiredStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _States_StreamReportedStateChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(shadowpb.StreamReportedStateChangesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StatesServer).StreamReportedStateChanges(m, &statesStreamReportedStateChangesServer{stream})
}

type States_StreamReportedStateChangesServer interface {
	Send(*shadowpb.StreamReportedStateChangesResponse) error
	grpc.ServerStream
}

type statesStreamReportedStateChangesServer struct {
	grpc.ServerStream
}

func (x *statesStreamReportedStateChangesServer) Send(m *shadowpb.StreamReportedStateChangesResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _States_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.api.States",
	HandlerType: (*StatesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _States_Get_Handler,
		},
		{
			MethodName: "PatchDesiredState",
			Handler:    _States_PatchDesiredState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamReportedStateChanges",
			Handler:       _States_StreamReportedStateChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/apiserver/apipb/api.proto",
}

// AccountsClient is the client API for Accounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsClient interface {
	SelfAccount(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*nodepb.Account, error)
	Token(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	CreateUserAccount(ctx context.Context, in *nodepb.CreateUserAccountRequest, opts ...grpc.CallOption) (*nodepb.CreateUserAccountResponse, error)
	GetAccount(ctx context.Context, in *nodepb.GetAccountRequest, opts ...grpc.CallOption) (*nodepb.Account, error)
	UpdateAccount(ctx context.Context, in *nodepb.UpdateAccountRequest, opts ...grpc.CallOption) (*nodepb.Account, error)
	ListAccounts(ctx context.Context, in *nodepb.ListAccountsRequest, opts ...grpc.CallOption) (*nodepb.ListAccountsResponse, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) SelfAccount(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*nodepb.Account, error) {
	out := new(nodepb.Account)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Accounts/SelfAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) Token(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Accounts/Token", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) CreateUserAccount(ctx context.Context, in *nodepb.CreateUserAccountRequest, opts ...grpc.CallOption) (*nodepb.CreateUserAccountResponse, error) {
	out := new(nodepb.CreateUserAccountResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Accounts/CreateUserAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) GetAccount(ctx context.Context, in *nodepb.GetAccountRequest, opts ...grpc.CallOption) (*nodepb.Account, error) {
	out := new(nodepb.Account)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Accounts/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) UpdateAccount(ctx context.Context, in *nodepb.UpdateAccountRequest, opts ...grpc.CallOption) (*nodepb.Account, error) {
	out := new(nodepb.Account)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Accounts/UpdateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) ListAccounts(ctx context.Context, in *nodepb.ListAccountsRequest, opts ...grpc.CallOption) (*nodepb.ListAccountsResponse, error) {
	out := new(nodepb.ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Accounts/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServer is the server API for Accounts service.
type AccountsServer interface {
	SelfAccount(context.Context, *empty.Empty) (*nodepb.Account, error)
	Token(context.Context, *TokenRequest) (*TokenResponse, error)
	CreateUserAccount(context.Context, *nodepb.CreateUserAccountRequest) (*nodepb.CreateUserAccountResponse, error)
	GetAccount(context.Context, *nodepb.GetAccountRequest) (*nodepb.Account, error)
	UpdateAccount(context.Context, *nodepb.UpdateAccountRequest) (*nodepb.Account, error)
	ListAccounts(context.Context, *nodepb.ListAccountsRequest) (*nodepb.ListAccountsResponse, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_SelfAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).SelfAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Accounts/SelfAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).SelfAccount(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_Token_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Token(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Accounts/Token",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Token(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_CreateUserAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(nodepb.CreateUserAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).CreateUserAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Accounts/CreateUserAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).CreateUserAccount(ctx, req.(*nodepb.CreateUserAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(nodepb.GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Accounts/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).GetAccount(ctx, req.(*nodepb.GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(nodepb.UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Accounts/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).UpdateAccount(ctx, req.(*nodepb.UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(nodepb.ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Accounts/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).ListAccounts(ctx, req.(*nodepb.ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.api.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelfAccount",
			Handler:    _Accounts_SelfAccount_Handler,
		},
		{
			MethodName: "Token",
			Handler:    _Accounts_Token_Handler,
		},
		{
			MethodName: "CreateUserAccount",
			Handler:    _Accounts_CreateUserAccount_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _Accounts_GetAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _Accounts_UpdateAccount_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _Accounts_ListAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apiserver/apipb/api.proto",
}

// ObjectsClient is the client API for Objects service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ObjectsClient interface {
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*nodepb.ListObjectsResponse, error)
	CreateObject(ctx context.Context, in *CreateObjectRequest, opts ...grpc.CallOption) (*nodepb.Object, error)
	DeleteObject(ctx context.Context, in *nodepb.DeleteObjectRequest, opts ...grpc.CallOption) (*nodepb.DeleteObjectResponse, error)
}

type objectsClient struct {
	cc *grpc.ClientConn
}

func NewObjectsClient(cc *grpc.ClientConn) ObjectsClient {
	return &objectsClient{cc}
}

func (c *objectsClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*nodepb.ListObjectsResponse, error) {
	out := new(nodepb.ListObjectsResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Objects/ListObjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectsClient) CreateObject(ctx context.Context, in *CreateObjectRequest, opts ...grpc.CallOption) (*nodepb.Object, error) {
	out := new(nodepb.Object)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Objects/CreateObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectsClient) DeleteObject(ctx context.Context, in *nodepb.DeleteObjectRequest, opts ...grpc.CallOption) (*nodepb.DeleteObjectResponse, error) {
	out := new(nodepb.DeleteObjectResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Objects/DeleteObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectsServer is the server API for Objects service.
type ObjectsServer interface {
	ListObjects(context.Context, *ListObjectsRequest) (*nodepb.ListObjectsResponse, error)
	CreateObject(context.Context, *CreateObjectRequest) (*nodepb.Object, error)
	DeleteObject(context.Context, *nodepb.DeleteObjectRequest) (*nodepb.DeleteObjectResponse, error)
}

func RegisterObjectsServer(s *grpc.Server, srv ObjectsServer) {
	s.RegisterService(&_Objects_serviceDesc, srv)
}

func _Objects_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectsServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Objects/ListObjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectsServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Objects_CreateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectsServer).CreateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Objects/CreateObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectsServer).CreateObject(ctx, req.(*CreateObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Objects_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(nodepb.DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectsServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Objects/DeleteObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectsServer).DeleteObject(ctx, req.(*nodepb.DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Objects_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.api.Objects",
	HandlerType: (*ObjectsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListObjects",
			Handler:    _Objects_ListObjects_Handler,
		},
		{
			MethodName: "CreateObject",
			Handler:    _Objects_CreateObject_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _Objects_DeleteObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apiserver/apipb/api.proto",
}

// NamespacesClient is the client API for Namespaces service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NamespacesClient interface {
	CreateNamespace(ctx context.Context, in *nodepb.CreateNamespaceRequest, opts ...grpc.CallOption) (*nodepb.Namespace, error)
	GetNamespace(ctx context.Context, in *nodepb.GetNamespaceRequest, opts ...grpc.CallOption) (*nodepb.Namespace, error)
	ListNamespaces(ctx context.Context, in *nodepb.ListNamespacesRequest, opts ...grpc.CallOption) (*nodepb.ListNamespacesResponse, error)
	CreatePermission(ctx context.Context, in *CreateNamespacePermissionRequest, opts ...grpc.CallOption) (*CreateNamespacePermissionResponse, error)
	ListPermissions(ctx context.Context, in *nodepb.ListPermissionsRequest, opts ...grpc.CallOption) (*nodepb.ListPermissionsResponse, error)
}

type namespacesClient struct {
	cc *grpc.ClientConn
}

func NewNamespacesClient(cc *grpc.ClientConn) NamespacesClient {
	return &namespacesClient{cc}
}

func (c *namespacesClient) CreateNamespace(ctx context.Context, in *nodepb.CreateNamespaceRequest, opts ...grpc.CallOption) (*nodepb.Namespace, error) {
	out := new(nodepb.Namespace)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Namespaces/CreateNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesClient) GetNamespace(ctx context.Context, in *nodepb.GetNamespaceRequest, opts ...grpc.CallOption) (*nodepb.Namespace, error) {
	out := new(nodepb.Namespace)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Namespaces/GetNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesClient) ListNamespaces(ctx context.Context, in *nodepb.ListNamespacesRequest, opts ...grpc.CallOption) (*nodepb.ListNamespacesResponse, error) {
	out := new(nodepb.ListNamespacesResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Namespaces/ListNamespaces", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesClient) CreatePermission(ctx context.Context, in *CreateNamespacePermissionRequest, opts ...grpc.CallOption) (*CreateNamespacePermissionResponse, error) {
	out := new(CreateNamespacePermissionResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Namespaces/CreatePermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *namespacesClient) ListPermissions(ctx context.Context, in *nodepb.ListPermissionsRequest, opts ...grpc.CallOption) (*nodepb.ListPermissionsResponse, error) {
	out := new(nodepb.ListPermissionsResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Namespaces/ListPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NamespacesServer is the server API for Namespaces service.
type NamespacesServer interface {
	CreateNamespace(context.Context, *nodepb.CreateNamespaceRequest) (*nodepb.Namespace, error)
	GetNamespace(context.Context, *nodepb.GetNamespaceRequest) (*nodepb.Namespace, error)
	ListNamespaces(context.Context, *nodepb.ListNamespacesRequest) (*nodepb.ListNamespacesResponse, error)
	CreatePermission(context.Context, *CreateNamespacePermissionRequest) (*CreateNamespacePermissionResponse, error)
	ListPermissions(context.Context, *nodepb.ListPermissionsRequest) (*nodepb.ListPermissionsResponse, error)
}

func RegisterNamespacesServer(s *grpc.Server, srv NamespacesServer) {
	s.RegisterService(&_Namespaces_serviceDesc, srv)
}

func _Namespaces_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(nodepb.CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Namespaces/CreateNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServer).CreateNamespace(ctx, req.(*nodepb.CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespaces_GetNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(nodepb.GetNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServer).GetNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Namespaces/GetNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServer).GetNamespace(ctx, req.(*nodepb.GetNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespaces_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(nodepb.ListNamespacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Namespaces/ListNamespaces",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServer).ListNamespaces(ctx, req.(*nodepb.ListNamespacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespaces_CreatePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespacePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServer).CreatePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Namespaces/CreatePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServer).CreatePermission(ctx, req.(*CreateNamespacePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Namespaces_ListPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(nodepb.ListPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NamespacesServer).ListPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Namespaces/ListPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NamespacesServer).ListPermissions(ctx, req.(*nodepb.ListPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Namespaces_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.api.Namespaces",
	HandlerType: (*NamespacesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNamespace",
			Handler:    _Namespaces_CreateNamespace_Handler,
		},
		{
			MethodName: "GetNamespace",
			Handler:    _Namespaces_GetNamespace_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _Namespaces_ListNamespaces_Handler,
		},
		{
			MethodName: "CreatePermission",
			Handler:    _Namespaces_CreatePermission_Handler,
		},
		{
			MethodName: "ListPermissions",
			Handler:    _Namespaces_ListPermissions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apiserver/apipb/api.proto",
}
