// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apiserver/apipb/api.proto

package apipb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	registrypb "github.com/infinimesh/infinimesh/pkg/registry/registrypb"
	shadowpb "github.com/infinimesh/infinimesh/pkg/shadow/shadowpb"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("pkg/apiserver/apipb/api.proto", fileDescriptor_06a22a27722afd30) }

var fileDescriptor_06a22a27722afd30 = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcd, 0x6a, 0x14, 0x41,
	0x10, 0xc7, 0x99, 0x68, 0x46, 0x6d, 0x41, 0xb3, 0x85, 0x10, 0x1d, 0x0c, 0x2e, 0x0b, 0xf1, 0x23,
	0x66, 0xa7, 0xe3, 0x8a, 0x97, 0x3d, 0x69, 0x12, 0x08, 0x01, 0x09, 0x12, 0x3d, 0x79, 0x91, 0xde,
	0x9d, 0xca, 0x6c, 0xc7, 0xd9, 0xee, 0xb6, 0xbb, 0xb3, 0x4b, 0x90, 0x20, 0xe8, 0xdd, 0x83, 0xbe,
	0x87, 0x77, 0x9f, 0xc3, 0x57, 0xf0, 0xea, 0x3b, 0xc8, 0xf4, 0xf4, 0x4c, 0x66, 0x12, 0xd8, 0xdd,
	0xcb, 0x4c, 0x51, 0xf5, 0xeb, 0xaa, 0x7f, 0x15, 0x55, 0x64, 0x4d, 0x7d, 0x4c, 0x29, 0x53, 0xdc,
	0xa0, 0x9e, 0xa0, 0xce, 0x2d, 0x35, 0xc8, 0xbf, 0xb1, 0xd2, 0xd2, 0x4a, 0xb8, 0xc5, 0xc5, 0x11,
	0x17, 0x7c, 0x8c, 0x66, 0x14, 0x33, 0xc5, 0xa3, 0x6e, 0x8e, 0x6b, 0x4c, 0xb9, 0xb1, 0xfa, 0xb4,
	0x32, 0xd4, 0x80, 0x26, 0x38, 0xe1, 0x43, 0xfc, 0x50, 0x7a, 0x8a, 0xe7, 0x51, 0x3b, 0xc7, 0xcd,
	0x88, 0x25, 0x72, 0xea, 0x7f, 0x6a, 0xe0, 0x0d, 0x4f, 0x6c, 0xba, 0xdf, 0xb0, 0x9b, 0xa2, 0xe8,
	0x9a, 0x29, 0x4b, 0x53, 0xd4, 0x54, 0x2a, 0xcb, 0xa5, 0x30, 0x94, 0x09, 0x21, 0x2d, 0x73, 0xb6,
	0xa7, 0xef, 0xa7, 0x52, 0xa6, 0x19, 0xe6, 0x02, 0x2f, 0x47, 0x7b, 0xff, 0xae, 0x90, 0x6b, 0xbb,
	0x4e, 0x87, 0x81, 0x29, 0x09, 0x77, 0x34, 0x32, 0x8b, 0xf0, 0x38, 0xae, 0xf5, 0x50, 0xc8, 0xac,
	0x54, 0x16, 0xc8, 0x21, 0x7e, 0x3a, 0x41, 0x63, 0xa3, 0x27, 0x0b, 0x90, 0x46, 0x49, 0x61, 0xb0,
	0x73, 0xf7, 0xeb, 0x9f, 0xbf, 0x3f, 0x97, 0xa0, 0x73, 0xdd, 0x37, 0x6e, 0xfa, 0x61, 0x61, 0xc0,
	0x17, 0x72, 0x63, 0x0f, 0xed, 0xf6, 0xe9, 0x01, 0x1b, 0x23, 0x3c, 0x9d, 0x91, 0xb1, 0xa2, 0xca,
	0xf2, 0x9b, 0x8b, 0xc1, 0x5e, 0xc1, 0xaa, 0x53, 0xd0, 0x82, 0xdb, 0xa5, 0x02, 0xfa, 0x59, 0xb0,
	0x31, 0x9e, 0x81, 0x22, 0x57, 0x5f, 0x73, 0x63, 0xa1, 0x3b, 0x23, 0x5d, 0x0e, 0xf8, 0x49, 0x95,
	0xd5, 0x1f, 0xcd, 0xc1, 0xab, 0xc2, 0x2b, 0xae, 0x30, 0x81, 0xaa, 0x75, 0x98, 0x90, 0x70, 0x17,
	0x33, 0x9c, 0x33, 0xeb, 0x02, 0x59, 0x64, 0xd6, 0x25, 0xd9, 0xec, 0x74, 0xe3, 0x62, 0xa7, 0xbd,
	0xef, 0x01, 0x09, 0xdf, 0xba, 0x65, 0x82, 0x6f, 0x01, 0xb9, 0xb9, 0x87, 0xf6, 0x10, 0x95, 0xd4,
	0x16, 0x13, 0x58, 0xaf, 0xa7, 0xf7, 0x0b, 0x57, 0x8b, 0x97, 0x2a, 0x1e, 0xce, 0xc3, 0xbc, 0x84,
	0x75, 0x27, 0xe1, 0x01, 0xac, 0x9d, 0x4b, 0xf0, 0x0b, 0xcf, 0x93, 0x33, 0xaa, 0x3d, 0xbe, 0xfd,
	0x3b, 0xf8, 0xf1, 0xea, 0x57, 0x00, 0x9a, 0xac, 0xee, 0x57, 0x69, 0xdb, 0xfb, 0xf2, 0x5d, 0xfb,
	0x4d, 0xc6, 0xec, 0x91, 0xd4, 0x63, 0xb8, 0xb7, 0x93, 0xc9, 0x93, 0xa4, 0x7d, 0xc0, 0x2c, 0x9f,
	0x60, 0x23, 0xd4, 0x79, 0x41, 0xc8, 0xf9, 0x2b, 0xb8, 0x33, 0xb2, 0x56, 0xf5, 0x29, 0xad, 0xe9,
	0xe3, 0x32, 0x6a, 0x1d, 0x4b, 0x7c, 0xd9, 0x70, 0xf5, 0x96, 0xb7, 0xe2, 0xad, 0xf8, 0x59, 0xd4,
	0xca, 0x6f, 0xb6, 0x11, 0xd9, 0x08, 0x96, 0x7a, 0x2b, 0x4c, 0xa9, 0x8c, 0x0f, 0xdd, 0x95, 0xd0,
	0x63, 0x23, 0x45, 0xff, 0x92, 0xe7, 0xfd, 0xb2, 0xbb, 0xf9, 0x41, 0xe8, 0x6e, 0xe8, 0xf9, 0xff,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0x7b, 0x71, 0x6f, 0x11, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DevicesClient is the client API for Devices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DevicesClient interface {
	Create(ctx context.Context, in *registrypb.CreateRequest, opts ...grpc.CallOption) (*registrypb.CreateResponse, error)
	GetByName(ctx context.Context, in *registrypb.GetByNameRequest, opts ...grpc.CallOption) (*registrypb.GetByNameResponse, error)
	List(ctx context.Context, in *registrypb.ListDevicesRequest, opts ...grpc.CallOption) (*registrypb.ListResponse, error)
	Delete(ctx context.Context, in *registrypb.DeleteRequest, opts ...grpc.CallOption) (*registrypb.DeleteResponse, error)
}

type devicesClient struct {
	cc *grpc.ClientConn
}

func NewDevicesClient(cc *grpc.ClientConn) DevicesClient {
	return &devicesClient{cc}
}

func (c *devicesClient) Create(ctx context.Context, in *registrypb.CreateRequest, opts ...grpc.CallOption) (*registrypb.CreateResponse, error) {
	out := new(registrypb.CreateResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Devices/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) GetByName(ctx context.Context, in *registrypb.GetByNameRequest, opts ...grpc.CallOption) (*registrypb.GetByNameResponse, error) {
	out := new(registrypb.GetByNameResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Devices/GetByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) List(ctx context.Context, in *registrypb.ListDevicesRequest, opts ...grpc.CallOption) (*registrypb.ListResponse, error) {
	out := new(registrypb.ListResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Devices/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) Delete(ctx context.Context, in *registrypb.DeleteRequest, opts ...grpc.CallOption) (*registrypb.DeleteResponse, error) {
	out := new(registrypb.DeleteResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Devices/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevicesServer is the server API for Devices service.
type DevicesServer interface {
	Create(context.Context, *registrypb.CreateRequest) (*registrypb.CreateResponse, error)
	GetByName(context.Context, *registrypb.GetByNameRequest) (*registrypb.GetByNameResponse, error)
	List(context.Context, *registrypb.ListDevicesRequest) (*registrypb.ListResponse, error)
	Delete(context.Context, *registrypb.DeleteRequest) (*registrypb.DeleteResponse, error)
}

func RegisterDevicesServer(s *grpc.Server, srv DevicesServer) {
	s.RegisterService(&_Devices_serviceDesc, srv)
}

func _Devices_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(registrypb.CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Devices/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).Create(ctx, req.(*registrypb.CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_GetByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(registrypb.GetByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).GetByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Devices/GetByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).GetByName(ctx, req.(*registrypb.GetByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(registrypb.ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Devices/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).List(ctx, req.(*registrypb.ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(registrypb.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Devices/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).Delete(ctx, req.(*registrypb.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Devices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.api.Devices",
	HandlerType: (*DevicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Devices_Create_Handler,
		},
		{
			MethodName: "GetByName",
			Handler:    _Devices_GetByName_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Devices_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Devices_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apiserver/apipb/api.proto",
}

// ShadowClient is the client API for Shadow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShadowClient interface {
	GetReported(ctx context.Context, in *shadowpb.GetReportedRequest, opts ...grpc.CallOption) (*shadowpb.GetReportedResponse, error)
}

type shadowClient struct {
	cc *grpc.ClientConn
}

func NewShadowClient(cc *grpc.ClientConn) ShadowClient {
	return &shadowClient{cc}
}

func (c *shadowClient) GetReported(ctx context.Context, in *shadowpb.GetReportedRequest, opts ...grpc.CallOption) (*shadowpb.GetReportedResponse, error) {
	out := new(shadowpb.GetReportedResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.api.Shadow/GetReported", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShadowServer is the server API for Shadow service.
type ShadowServer interface {
	GetReported(context.Context, *shadowpb.GetReportedRequest) (*shadowpb.GetReportedResponse, error)
}

func RegisterShadowServer(s *grpc.Server, srv ShadowServer) {
	s.RegisterService(&_Shadow_serviceDesc, srv)
}

func _Shadow_GetReported_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(shadowpb.GetReportedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShadowServer).GetReported(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.api.Shadow/GetReported",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShadowServer).GetReported(ctx, req.(*shadowpb.GetReportedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shadow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.api.Shadow",
	HandlerType: (*ShadowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReported",
			Handler:    _Shadow_GetReported_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apiserver/apipb/api.proto",
}
