// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avrorepo.proto

package main.java.proto;

public interface DeviceStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.DeviceState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes reportedState = 3;</code>
   * @return The reportedState.
   */
  com.google.protobuf.ByteString getReportedState();

  /**
   * <code>bytes desiredState = 4;</code>
   * @return The desiredState.
   */
  com.google.protobuf.ByteString getDesiredState();
}
