// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avrorepo.proto

package main.java.proto;

public interface SaveDeviceStateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.SaveDeviceStateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();
}
