// Code generated by mockery v2.40.1. DO NOT EDIT.

package node_mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	node "github.com/infinimesh/proto/node"

	sessions "github.com/infinimesh/proto/node/sessions"
)

// MockSessionsServiceClient is an autogenerated mock type for the SessionsServiceClient type
type MockSessionsServiceClient struct {
	mock.Mock
}

type MockSessionsServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionsServiceClient) EXPECT() *MockSessionsServiceClient_Expecter {
	return &MockSessionsServiceClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, in, opts
func (_m *MockSessionsServiceClient) Get(ctx context.Context, in *node.EmptyMessage, opts ...grpc.CallOption) (*sessions.Sessions, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *sessions.Sessions
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *node.EmptyMessage, ...grpc.CallOption) (*sessions.Sessions, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *node.EmptyMessage, ...grpc.CallOption) *sessions.Sessions); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sessions.Sessions)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *node.EmptyMessage, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionsServiceClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionsServiceClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - in *node.EmptyMessage
//   - opts ...grpc.CallOption
func (_e *MockSessionsServiceClient_Expecter) Get(ctx interface{}, in interface{}, opts ...interface{}) *MockSessionsServiceClient_Get_Call {
	return &MockSessionsServiceClient_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockSessionsServiceClient_Get_Call) Run(run func(ctx context.Context, in *node.EmptyMessage, opts ...grpc.CallOption)) *MockSessionsServiceClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*node.EmptyMessage), variadicArgs...)
	})
	return _c
}

func (_c *MockSessionsServiceClient_Get_Call) Return(_a0 *sessions.Sessions, _a1 error) *MockSessionsServiceClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionsServiceClient_Get_Call) RunAndReturn(run func(context.Context, *node.EmptyMessage, ...grpc.CallOption) (*sessions.Sessions, error)) *MockSessionsServiceClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetActivity provides a mock function with given fields: ctx, in, opts
func (_m *MockSessionsServiceClient) GetActivity(ctx context.Context, in *node.EmptyMessage, opts ...grpc.CallOption) (*sessions.Activity, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetActivity")
	}

	var r0 *sessions.Activity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *node.EmptyMessage, ...grpc.CallOption) (*sessions.Activity, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *node.EmptyMessage, ...grpc.CallOption) *sessions.Activity); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sessions.Activity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *node.EmptyMessage, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionsServiceClient_GetActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActivity'
type MockSessionsServiceClient_GetActivity_Call struct {
	*mock.Call
}

// GetActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - in *node.EmptyMessage
//   - opts ...grpc.CallOption
func (_e *MockSessionsServiceClient_Expecter) GetActivity(ctx interface{}, in interface{}, opts ...interface{}) *MockSessionsServiceClient_GetActivity_Call {
	return &MockSessionsServiceClient_GetActivity_Call{Call: _e.mock.On("GetActivity",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockSessionsServiceClient_GetActivity_Call) Run(run func(ctx context.Context, in *node.EmptyMessage, opts ...grpc.CallOption)) *MockSessionsServiceClient_GetActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*node.EmptyMessage), variadicArgs...)
	})
	return _c
}

func (_c *MockSessionsServiceClient_GetActivity_Call) Return(_a0 *sessions.Activity, _a1 error) *MockSessionsServiceClient_GetActivity_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionsServiceClient_GetActivity_Call) RunAndReturn(run func(context.Context, *node.EmptyMessage, ...grpc.CallOption) (*sessions.Activity, error)) *MockSessionsServiceClient_GetActivity_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, in, opts
func (_m *MockSessionsServiceClient) Revoke(ctx context.Context, in *sessions.Session, opts ...grpc.CallOption) (*node.DeleteResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 *node.DeleteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sessions.Session, ...grpc.CallOption) (*node.DeleteResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sessions.Session, ...grpc.CallOption) *node.DeleteResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*node.DeleteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sessions.Session, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionsServiceClient_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockSessionsServiceClient_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - in *sessions.Session
//   - opts ...grpc.CallOption
func (_e *MockSessionsServiceClient_Expecter) Revoke(ctx interface{}, in interface{}, opts ...interface{}) *MockSessionsServiceClient_Revoke_Call {
	return &MockSessionsServiceClient_Revoke_Call{Call: _e.mock.On("Revoke",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockSessionsServiceClient_Revoke_Call) Run(run func(ctx context.Context, in *sessions.Session, opts ...grpc.CallOption)) *MockSessionsServiceClient_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*sessions.Session), variadicArgs...)
	})
	return _c
}

func (_c *MockSessionsServiceClient_Revoke_Call) Return(_a0 *node.DeleteResponse, _a1 error) *MockSessionsServiceClient_Revoke_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionsServiceClient_Revoke_Call) RunAndReturn(run func(context.Context, *sessions.Session, ...grpc.CallOption) (*node.DeleteResponse, error)) *MockSessionsServiceClient_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionsServiceClient creates a new instance of MockSessionsServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionsServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionsServiceClient {
	mock := &MockSessionsServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
