// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/registry/registrypb/device_registry.proto

package registrypb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Device struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Enabled              bool         `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Certificate          *Certificate `protobuf:"bytes,4,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Tags                 []string     `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff97fec4b2fb717, []int{0}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Device) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Device) GetCertificate() *Certificate {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func (m *Device) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type CreateRequest struct {
	Device               *Device  `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff97fec4b2fb717, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type Certificate struct {
	PemData              string   `protobuf:"bytes,1,opt,name=pem_data,json=pemData,proto3" json:"pem_data,omitempty"`
	Algorithm            string   `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	ValidTo              uint64   `protobuf:"varint,3,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Certificate) Reset()         { *m = Certificate{} }
func (m *Certificate) String() string { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()    {}
func (*Certificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff97fec4b2fb717, []int{2}
}

func (m *Certificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Certificate.Unmarshal(m, b)
}
func (m *Certificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Certificate.Marshal(b, m, deterministic)
}
func (m *Certificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Certificate.Merge(m, src)
}
func (m *Certificate) XXX_Size() int {
	return xxx_messageInfo_Certificate.Size(m)
}
func (m *Certificate) XXX_DiscardUnknown() {
	xxx_messageInfo_Certificate.DiscardUnknown(m)
}

var xxx_messageInfo_Certificate proto.InternalMessageInfo

func (m *Certificate) GetPemData() string {
	if m != nil {
		return m.PemData
	}
	return ""
}

func (m *Certificate) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *Certificate) GetValidTo() uint64 {
	if m != nil {
		return m.ValidTo
	}
	return 0
}

type CreateResponse struct {
	Fingerprint          []byte   `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff97fec4b2fb717, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetFingerprint() []byte {
	if m != nil {
		return m.Fingerprint
	}
	return nil
}

type GetByFingerprintRequest struct {
	Fingerprint          []byte   `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByFingerprintRequest) Reset()         { *m = GetByFingerprintRequest{} }
func (m *GetByFingerprintRequest) String() string { return proto.CompactTextString(m) }
func (*GetByFingerprintRequest) ProtoMessage()    {}
func (*GetByFingerprintRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff97fec4b2fb717, []int{4}
}

func (m *GetByFingerprintRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByFingerprintRequest.Unmarshal(m, b)
}
func (m *GetByFingerprintRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByFingerprintRequest.Marshal(b, m, deterministic)
}
func (m *GetByFingerprintRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByFingerprintRequest.Merge(m, src)
}
func (m *GetByFingerprintRequest) XXX_Size() int {
	return xxx_messageInfo_GetByFingerprintRequest.Size(m)
}
func (m *GetByFingerprintRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByFingerprintRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByFingerprintRequest proto.InternalMessageInfo

func (m *GetByFingerprintRequest) GetFingerprint() []byte {
	if m != nil {
		return m.Fingerprint
	}
	return nil
}

type GetByFingerprintResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByFingerprintResponse) Reset()         { *m = GetByFingerprintResponse{} }
func (m *GetByFingerprintResponse) String() string { return proto.CompactTextString(m) }
func (*GetByFingerprintResponse) ProtoMessage()    {}
func (*GetByFingerprintResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff97fec4b2fb717, []int{5}
}

func (m *GetByFingerprintResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByFingerprintResponse.Unmarshal(m, b)
}
func (m *GetByFingerprintResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByFingerprintResponse.Marshal(b, m, deterministic)
}
func (m *GetByFingerprintResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByFingerprintResponse.Merge(m, src)
}
func (m *GetByFingerprintResponse) XXX_Size() int {
	return xxx_messageInfo_GetByFingerprintResponse.Size(m)
}
func (m *GetByFingerprintResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByFingerprintResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByFingerprintResponse proto.InternalMessageInfo

func (m *GetByFingerprintResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff97fec4b2fb717, []int{6}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Device               *Device  `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff97fec4b2fb717, []int{7}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type ListDevicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDevicesRequest) Reset()         { *m = ListDevicesRequest{} }
func (m *ListDevicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListDevicesRequest) ProtoMessage()    {}
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff97fec4b2fb717, []int{8}
}

func (m *ListDevicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDevicesRequest.Unmarshal(m, b)
}
func (m *ListDevicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDevicesRequest.Marshal(b, m, deterministic)
}
func (m *ListDevicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDevicesRequest.Merge(m, src)
}
func (m *ListDevicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListDevicesRequest.Size(m)
}
func (m *ListDevicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDevicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDevicesRequest proto.InternalMessageInfo

type ListResponse struct {
	Devices              []*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff97fec4b2fb717, []int{9}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type DeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff97fec4b2fb717, []int{10}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ff97fec4b2fb717, []int{11}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Device)(nil), "infinimesh.deviceregistry.Device")
	proto.RegisterType((*CreateRequest)(nil), "infinimesh.deviceregistry.CreateRequest")
	proto.RegisterType((*Certificate)(nil), "infinimesh.deviceregistry.Certificate")
	proto.RegisterType((*CreateResponse)(nil), "infinimesh.deviceregistry.CreateResponse")
	proto.RegisterType((*GetByFingerprintRequest)(nil), "infinimesh.deviceregistry.GetByFingerprintRequest")
	proto.RegisterType((*GetByFingerprintResponse)(nil), "infinimesh.deviceregistry.GetByFingerprintResponse")
	proto.RegisterType((*GetRequest)(nil), "infinimesh.deviceregistry.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "infinimesh.deviceregistry.GetResponse")
	proto.RegisterType((*ListDevicesRequest)(nil), "infinimesh.deviceregistry.ListDevicesRequest")
	proto.RegisterType((*ListResponse)(nil), "infinimesh.deviceregistry.ListResponse")
	proto.RegisterType((*DeleteRequest)(nil), "infinimesh.deviceregistry.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "infinimesh.deviceregistry.DeleteResponse")
}

func init() {
	proto.RegisterFile("pkg/registry/registrypb/device_registry.proto", fileDescriptor_4ff97fec4b2fb717)
}

var fileDescriptor_4ff97fec4b2fb717 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xd1, 0x6a, 0xdb, 0x30,
	0x14, 0xc5, 0x71, 0x16, 0x37, 0xd7, 0x69, 0x28, 0x97, 0xc1, 0xdc, 0x50, 0x98, 0x67, 0x58, 0xe7,
	0x0d, 0x9a, 0x82, 0xfb, 0x34, 0xfa, 0xd6, 0x86, 0xa5, 0x6c, 0x7b, 0x32, 0x7d, 0x1a, 0x74, 0x41,
	0x89, 0x6f, 0x5c, 0xb1, 0xc4, 0xf6, 0x2c, 0xad, 0x50, 0xf6, 0x13, 0xfb, 0xde, 0x3d, 0x0d, 0xcb,
	0x72, 0x9c, 0xa6, 0xd4, 0xc9, 0xe8, 0x9b, 0x74, 0x74, 0xce, 0x3d, 0xba, 0x3a, 0xe2, 0xc2, 0x49,
	0xf6, 0x23, 0x3e, 0xcd, 0x29, 0xe6, 0x42, 0xe6, 0xf7, 0xab, 0x45, 0x36, 0x3d, 0x8d, 0xe8, 0x8e,
	0xcf, 0x68, 0x52, 0x21, 0xc3, 0x2c, 0x4f, 0x65, 0x8a, 0x87, 0x3c, 0x99, 0xf3, 0x84, 0x2f, 0x49,
	0xdc, 0x0e, 0x4b, 0x46, 0x45, 0xf0, 0xfe, 0x18, 0xd0, 0x19, 0x29, 0x08, 0xfb, 0xd0, 0xe2, 0x91,
	0x63, 0xb8, 0x86, 0xdf, 0x0d, 0x5b, 0x3c, 0x42, 0x07, 0x2c, 0x4a, 0xd8, 0x74, 0x41, 0x91, 0x63,
	0xba, 0x86, 0xbf, 0x17, 0x56, 0x5b, 0xbc, 0x02, 0x7b, 0x46, 0xb9, 0xe4, 0x73, 0x3e, 0x63, 0x92,
	0x9c, 0xb6, 0x6b, 0xf8, 0x76, 0x70, 0x3c, 0x7c, 0xd2, 0x65, 0x78, 0x59, 0xb3, 0xc3, 0x75, 0x29,
	0x22, 0xb4, 0x25, 0x8b, 0x85, 0xf3, 0xc2, 0x35, 0xfd, 0x6e, 0xa8, 0xd6, 0xde, 0x67, 0xd8, 0xbf,
	0xcc, 0xa9, 0xa0, 0xd2, 0xcf, 0x5f, 0x24, 0x24, 0x7e, 0x84, 0x4e, 0x59, 0x4f, 0x5d, 0xce, 0x0e,
	0xde, 0x34, 0x38, 0x95, 0xbd, 0x84, 0x5a, 0xe0, 0x31, 0xb0, 0xd7, 0xbc, 0xf1, 0x10, 0xf6, 0x32,
	0x5a, 0x4e, 0x22, 0x26, 0x99, 0x6e, 0xd4, 0xca, 0x68, 0x39, 0x62, 0x92, 0xe1, 0x11, 0x74, 0xd9,
	0x22, 0x4e, 0x73, 0x2e, 0x6f, 0x97, 0x4e, 0x4b, 0x9d, 0xd5, 0x40, 0x21, 0xbc, 0x63, 0x0b, 0x1e,
	0x4d, 0x64, 0xaa, 0x1e, 0xa3, 0x1d, 0x5a, 0x6a, 0x7f, 0x9d, 0x7a, 0x01, 0xf4, 0xab, 0xeb, 0x8a,
	0x2c, 0x4d, 0x04, 0xa1, 0x0b, 0xf6, 0x9c, 0x27, 0x31, 0xe5, 0x59, 0xce, 0x13, 0xa9, 0x8c, 0x7a,
	0xe1, 0x3a, 0xe4, 0x9d, 0xc3, 0xab, 0x31, 0xc9, 0x8b, 0xfb, 0x4f, 0x35, 0x56, 0x35, 0xbb, 0x5d,
	0xfc, 0x01, 0x9c, 0xc7, 0x62, 0x6d, 0xbd, 0x91, 0xa1, 0x77, 0x04, 0x30, 0xa6, 0x55, 0xed, 0xcd,
	0xd3, 0x2b, 0xb0, 0xd5, 0xa9, 0x16, 0x3f, 0xe3, 0x9d, 0x5f, 0x02, 0x7e, 0xe5, 0x42, 0x96, 0xa8,
	0xd0, 0x7e, 0xde, 0x17, 0xe8, 0x15, 0xe8, 0xca, 0xe0, 0x1c, 0xac, 0x92, 0x2f, 0x1c, 0xc3, 0x35,
	0x77, 0x73, 0xa8, 0x14, 0xde, 0x6b, 0xd8, 0x1f, 0xd1, 0x82, 0xea, 0x6f, 0xb1, 0xd9, 0xcd, 0x01,
	0xf4, 0x2b, 0x42, 0xe9, 0x17, 0xfc, 0x35, 0xc1, 0xd2, 0x57, 0xc2, 0x1b, 0xe8, 0x94, 0x31, 0xa1,
	0xdf, 0xf4, 0x51, 0xd7, 0x3f, 0xde, 0xe0, 0xfd, 0x0e, 0x4c, 0xdd, 0xda, 0x6f, 0x38, 0xd8, 0x0c,
	0x05, 0x83, 0x06, 0xf9, 0x13, 0xf1, 0x0f, 0xce, 0xfe, 0x4b, 0xa3, 0xcd, 0xaf, 0xc1, 0x1c, 0x93,
	0xc4, 0xb7, 0xcd, 0xda, 0xca, 0xe2, 0x78, 0x1b, 0x4d, 0x57, 0xfd, 0x0e, 0xed, 0x22, 0x3d, 0x3c,
	0x69, 0xe0, 0x3f, 0x0e, 0x7d, 0xf0, 0x6e, 0x0b, 0x7d, 0x55, 0xff, 0xa6, 0x98, 0x3c, 0x45, 0x5e,
	0x8d, 0x89, 0x3c, 0xc8, 0xbc, 0x31, 0x91, 0x87, 0xe1, 0x5f, 0xf4, 0xbe, 0x41, 0x3d, 0x18, 0xa7,
	0x1d, 0x35, 0x09, 0xcf, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x85, 0xdb, 0x7b, 0x69, 0x3a, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DevicesClient is the client API for Devices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DevicesClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	GetByFingerprint(ctx context.Context, in *GetByFingerprintRequest, opts ...grpc.CallOption) (*GetByFingerprintResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	List(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type devicesClient struct {
	cc *grpc.ClientConn
}

func NewDevicesClient(cc *grpc.ClientConn) DevicesClient {
	return &devicesClient{cc}
}

func (c *devicesClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.deviceregistry.Devices/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) GetByFingerprint(ctx context.Context, in *GetByFingerprintRequest, opts ...grpc.CallOption) (*GetByFingerprintResponse, error) {
	out := new(GetByFingerprintResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.deviceregistry.Devices/GetByFingerprint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.deviceregistry.Devices/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) List(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.deviceregistry.Devices/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *devicesClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/infinimesh.deviceregistry.Devices/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DevicesServer is the server API for Devices service.
type DevicesServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	GetByFingerprint(context.Context, *GetByFingerprintRequest) (*GetByFingerprintResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	List(context.Context, *ListDevicesRequest) (*ListResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterDevicesServer(s *grpc.Server, srv DevicesServer) {
	s.RegisterService(&_Devices_serviceDesc, srv)
}

func _Devices_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.deviceregistry.Devices/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_GetByFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByFingerprintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).GetByFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.deviceregistry.Devices/GetByFingerprint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).GetByFingerprint(ctx, req.(*GetByFingerprintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.deviceregistry.Devices/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.deviceregistry.Devices/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).List(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Devices_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DevicesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infinimesh.deviceregistry.Devices/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DevicesServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Devices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.deviceregistry.Devices",
	HandlerType: (*DevicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Devices_Create_Handler,
		},
		{
			MethodName: "GetByFingerprint",
			Handler:    _Devices_GetByFingerprint_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Devices_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Devices_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Devices_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/registry/registrypb/device_registry.proto",
}
